plugins{
    id 'java-library'
    id 'maven-publish'
}
dependencies {
    implementation project(':rosjava')
    implementation 'com.google.guava:guava:33.0.0-jre'
    implementation 'org.yaml:snakeyaml:2.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
    testImplementation project(':rosjava').sourceSets.test.output
}

jar {
    manifest {
        version = project.version
//    attributes 'symbolicName' : 'org.ros.rosjava'
//    instruction 'Export-Package', '!org.ros.internal.*, org.ros.*'
//    instruction 'Private-Package', 'org.ros.internal.*'
    }
}

publishing {
    final repositoryDirectory = "ROS_MAVEN_DEPLOYMENT_REPOSITORY"
    final mavenDeploymentRepositoryProvider = providers.gradleProperty(repositoryDirectory)
    final mavenDeploymentRepository  = mavenDeploymentRepositoryProvider.getOrElse(null)
//    println(repositoryDirectory + " = " + mavenDeploymentRepository);
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    if (mavenDeploymentRepository!=null) {
        repositories {
            maven {
                name "GithubRepositoryLocation"
                url 'file:////' + mavenDeploymentRepository
            }
        }
    } else {
        logger.debug(repositoryDirectory + "not found")
    }
}

test {
    useJUnitPlatform()
}