dependencies {
    implementation project(':rosjava')
    implementation 'com.google.guava:guava:33.0.0-jre'
    implementation 'org.yaml:snakeyaml:2.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
    testImplementation project(':rosjava').sourceSets.test.output
}
test {
    useJUnitPlatform()
}